id: 442dc7f8042247eb8aa88088b2e3811f
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_736-The_Dharani_of_Parnasavari-v2
  language: bo
  author: ''
  volume: {}
